"""buscas table

Revision ID: 53a2f00f645c
Revises: 4a2149588565
Create Date: 2021-11-12 12:29:35.947365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53a2f00f645c'
down_revision = '4a2149588565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('busca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('alternate_names', sa.String(length=140), nullable=True),
    sa.Column('species', sa.String(length=140), nullable=True),
    sa.Column('gender', sa.String(length=140), nullable=True),
    sa.Column('house', sa.String(length=140), nullable=True),
    sa.Column('dateOfBirth', sa.String(length=140), nullable=True),
    sa.Column('yearOfBirth', sa.String(length=140), nullable=True),
    sa.Column('wizard', sa.String(length=140), nullable=True),
    sa.Column('ancestry', sa.String(length=140), nullable=True),
    sa.Column('eyeColour', sa.String(length=140), nullable=True),
    sa.Column('hairColour', sa.String(length=140), nullable=True),
    sa.Column('wand', sa.String(length=140), nullable=True),
    sa.Column('patronus', sa.String(length=140), nullable=True),
    sa.Column('hogwartsStudent', sa.String(length=140), nullable=True),
    sa.Column('hogwartsStaff', sa.String(length=140), nullable=True),
    sa.Column('actor', sa.String(length=140), nullable=True),
    sa.Column('alternate_actors', sa.String(length=140), nullable=True),
    sa.Column('alive', sa.String(length=140), nullable=True),
    sa.Column('image', sa.String(length=140), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('busca')
    # ### end Alembic commands ###
